"""The bundle must refuse to ship a generated file no generator re-emitted.

Packaging regenerates every derived table, figure and macro into a staging
tree, then copies the hand-written sources in around them. A machine-generated
file that survives that copy is by definition one the current generators did
not produce, which means it was written by an older run against an older ledger.
Shipping it would put a stale number in the manuscript, so collection aborts.
"""

from __future__ import annotations

import pytest

from scripts.make_paper_bundle import (
    GENERATED_MARKER,
    PAPER,
    TREES,
    WRAP_WIDTH,
    collect,
    inspect_log,
    is_generated,
)

GENERATORS = ("make_paper_tables.py", "make_paper_figures.py", "analyze_robustness.py")


def test_every_generator_in_the_repo_is_recognized_by_the_marker():
    for script in GENERATORS:
        assert is_marker(f"% Generated by scripts/{script} -- do not edit by hand.")


def is_marker(first_line: str) -> bool:
    return first_line.startswith(GENERATED_MARKER)


def test_hand_written_sections_are_not_mistaken_for_generated_files():
    sections = sorted((PAPER / "sections").glob("*.tex"))
    assert sections, "expected the manuscript sections to exist"
    assert not [path.name for path in sections if is_generated(path)]


def test_collect_refuses_a_generated_file_the_generators_did_not_emit(tmp_path):
    stage = tmp_path / "stage"
    (stage / "tables").mkdir(parents=True)
    stale = PAPER / "tables" / "_stale_probe.tex"
    stale.write_text(
        f"{GENERATED_MARKER}analyze_robustness.py -- do not edit by hand.\n"
        "\\newcommand{\\robustProbe}{999}\n",
        encoding="utf-8",
    )
    try:
        with pytest.raises(SystemExit, match="machine-generated"):
            collect(stage)
    finally:
        stale.unlink()


def test_collect_accepts_generated_files_the_generators_did_emit(tmp_path):
    """The guard keys on absence from the staging tree, not on the marker itself.

    Standing in for a real generator run, this pre-stages every generated file
    under paper/ and checks that collection then copies the hand-written sources
    in without complaint.
    """
    stage = tmp_path / "stage"
    for tree in TREES:
        for path in (PAPER / tree).rglob("*.tex"):
            if not is_generated(path):
                continue
            target = stage / path.relative_to(PAPER)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    collect(stage)
    assert (stage / "main.tex").exists()
    assert (stage / "sections" / "results.tex").exists()


def test_the_trees_the_bundle_walks_still_exist():
    for tree in TREES:
        assert (PAPER / tree).is_dir()


CLEAN_LOG = "This is pdfTeX\nOutput written on main.pdf (16 pages, 566393 bytes).\n"


def log(tmp_path, text: str):
    path = tmp_path / "main.log"
    path.write_text(text, encoding="utf-8")
    return path


def test_a_clean_log_reports_its_page_count(tmp_path):
    assert inspect_log(log(tmp_path, CLEAN_LOG)) == 16


def test_an_undefined_macro_fails_the_verification_build(tmp_path):
    """An undefined macro typesets nothing and would drop a number in silence.

    The \\generated wrapper stops a missing table file, but a table that exists
    while its macros do not is the same defect one layer down, and this is the
    only thing standing between that and a published blank.
    """
    text = CLEAN_LOG + "! Undefined control sequence.\nl.42 \\robustControlTrust\n"
    with pytest.raises(SystemExit, match="Undefined control sequence"):
        inspect_log(log(tmp_path, text))


def test_unresolved_references_and_citations_fail_the_build(tmp_path):
    for warning in (
        "LaTeX Warning: Reference `tab:absent' on page 3 undefined on input line 9.",
        "LaTeX Warning: Citation `nobody2020' on page 3 undefined on input line 9.",
    ):
        with pytest.raises(SystemExit, match="not clean"):
            inspect_log(log(tmp_path, CLEAN_LOG + warning + "\n"))


def test_a_problem_wrapped_across_lines_is_still_seen(tmp_path):
    """TeX wraps its log at a fixed width, splitting the very lines checked."""
    prefix = "! Undefined control sequence"
    padding = "x" * (WRAP_WIDTH - len(prefix))
    text = CLEAN_LOG + f"{prefix}{padding}\n and the rest of the message\n"
    with pytest.raises(SystemExit, match="Undefined control sequence"):
        inspect_log(log(tmp_path, text))


def test_a_log_without_output_is_not_read_as_a_successful_build(tmp_path):
    with pytest.raises(SystemExit, match="no output file"):
        inspect_log(log(tmp_path, "This is pdfTeX\n"))
