"""The bundle must refuse to ship a generated file no generator re-emitted.

Packaging regenerates every derived table, figure and macro into a staging
tree, then copies the hand-written sources in around them. A machine-generated
file that survives that copy is by definition one the current generators did
not produce, which means it was written by an older run against an older ledger.
Shipping it would put a stale number in the manuscript, so collection aborts.
"""

from __future__ import annotations

import pytest

from scripts.make_paper_bundle import GENERATED_MARKER, PAPER, TREES, collect, is_generated

GENERATORS = ("make_paper_tables.py", "make_paper_figures.py", "analyze_robustness.py")


def test_every_generator_in_the_repo_is_recognized_by_the_marker():
    for script in GENERATORS:
        assert is_marker(f"% Generated by scripts/{script} -- do not edit by hand.")


def is_marker(first_line: str) -> bool:
    return first_line.startswith(GENERATED_MARKER)


def test_hand_written_sections_are_not_mistaken_for_generated_files():
    sections = sorted((PAPER / "sections").glob("*.tex"))
    assert sections, "expected the manuscript sections to exist"
    assert not [path.name for path in sections if is_generated(path)]


def test_collect_refuses_a_generated_file_the_generators_did_not_emit(tmp_path):
    stage = tmp_path / "stage"
    (stage / "tables").mkdir(parents=True)
    stale = PAPER / "tables" / "_stale_probe.tex"
    stale.write_text(
        f"{GENERATED_MARKER}analyze_robustness.py -- do not edit by hand.\n"
        "\\newcommand{\\robustProbe}{999}\n",
        encoding="utf-8",
    )
    try:
        with pytest.raises(SystemExit, match="machine-generated"):
            collect(stage)
    finally:
        stale.unlink()


def test_collect_accepts_generated_files_the_generators_did_emit(tmp_path):
    """The guard keys on absence from the staging tree, not on the marker itself.

    Standing in for a real generator run, this pre-stages every generated file
    under paper/ and checks that collection then copies the hand-written sources
    in without complaint.
    """
    stage = tmp_path / "stage"
    for tree in TREES:
        for path in (PAPER / tree).rglob("*.tex"):
            if not is_generated(path):
                continue
            target = stage / path.relative_to(PAPER)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    collect(stage)
    assert (stage / "main.tex").exists()
    assert (stage / "sections" / "results.tex").exists()


def test_the_trees_the_bundle_walks_still_exist():
    for tree in TREES:
        assert (PAPER / tree).is_dir()
