"""Summarize the corruption sweep and measure the mechanism behind it.

The sweep's most distinctive result is that masking the most recent history
block costs far more than any noise or scattered-missingness level, and that the
cost stops growing once the block passes a certain length. That saturation point
is a property of the architecture, not of the data: it is the number of trailing
timesteps the readout can still see.

That number is measured by scripts/run_receptive_field.py, on retrained weights
that reproduce the benchmark ledger, and is read here rather than recomputed.
Measuring it on a freshly initialized model would answer a question about the
architecture; the paper needs the answer for the models it reports, so the
measurement belongs with the runners that can prove which models those are.
Reported beside the sweep, it turns "the model is fragile to recent gaps" into a
statement about how much of the history each architecture actually consumes.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

try:
    import _bootstrap  # noqa: F401  # file-path execution
except ModuleNotFoundError:
    from scripts import _bootstrap  # noqa: F401  # module execution

from scripts.run_robustness_campaign import MODELS

ROOT = Path(__file__).resolve().parents[1]
GRID = ROOT / "results" / "robustness" / "aggregated" / "cet_robustness_grid.csv"
FIELDS = ROOT / "results" / "robustness" / "aggregated" / "cet_receptive_fields.csv"
LABELS = {"trustkan": "TrustKAN", "kan": "KAN (plain)", "transformer": "Transformer"}
KIND_LABELS = {
    "noise": "Gaussian noise",
    "random_missing": "Random missing",
    "block_missing": "Recent block missing",
}


def receptive_fields() -> pd.DataFrame:
    """One reach per model, from the runner's ledger-verified measurements.

    The runner measures every horizon separately. A reach that varied with the
    horizon would mean the number describes a trained instance rather than the
    architecture, so disagreement is refused rather than averaged away.
    """
    if not FIELDS.exists():
        raise SystemExit(
            f"missing {FIELDS.relative_to(ROOT)}; run scripts/run_receptive_field.py"
        )
    frame = pd.read_csv(FIELDS)
    spread = frame.groupby("model").receptive_field.nunique()
    if (spread > 1).any():
        raise SystemExit(
            f"receptive field varies with horizon for {list(spread[spread > 1].index)}; "
            "it cannot be reported as a property of the architecture"
        )
    if not frame.reproduced.all():
        raise SystemExit("some receptive-field runs did not reproduce the ledger RMSE")
    rows = frame.groupby("model", as_index=False).agg(
        history=("history", "first"),
        receptive_field=("receptive_field", "first"),
        control_receptive_field=("control_receptive_field", "first"),
        horizons=("horizon", "nunique"),
    )
    rows["history_used"] = rows.receptive_field / rows.history
    for row in rows.itertuples():
        print(
            f"  {LABELS[row.model]:<12} sees {row.receptive_field} of {row.history} "
            f"timesteps across {row.horizons} horizons "
            f"(untrained control {row.control_receptive_field})"
        )
    return rows


def robustness_table(grid: pd.DataFrame, fields: pd.DataFrame, out: Path) -> None:
    stats = (
        grid[grid.kind.ne("clean")]
        .groupby(["model", "kind", "level"])
        .relative_increase.mean()
        .mul(100)
    )
    reach = fields.set_index("model").receptive_field
    lines = [
        "% Generated by scripts/analyze_robustness.py -- do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Robustness on CET: percentage increase in test RMSE over the "
        r"clean forecast, averaged over four horizons and five seeds, on the "
        r"pre-registered corruption grid applied to test histories only. Masking "
        r"the most recent days costs far more than any other corruption, and for "
        r"TrustKAN the cost stops growing past three days, which is the number of "
        r"trailing timesteps its readout can see.}",
        r"\label{tab:cet_robustness}",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Corruption & Level & "
        + " & ".join(LABELS[name] for name in MODELS)
        + r" \\",
        r"\midrule",
    ]
    for kind, label in KIND_LABELS.items():
        levels = sorted({level for name, k, level in stats.index if k == kind})
        for index, level in enumerate(levels):
            cells = []
            for name in MODELS:
                key = (name, kind, level)
                cells.append(f"{stats[key]:.1f}" if key in stats.index else "--")
            shown = f"{level:g}" if kind != "block_missing" else f"{int(level)}\\,d"
            first = label if index == 0 else ""
            lines.append(f"{first} & {shown} & " + " & ".join(cells) + r" \\")
        lines.append(r"\addlinespace")
    lines += [
        r"\midrule",
        r"History visible to the readout & &"
        + " & ".join(
            f" {int(reach[name])} of {int(fields.history.iloc[0])} " for name in MODELS
        )
        + r" \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {log_path(out)}")


def log_path(path: Path) -> str:
    """Path for logging, which must never be able to abort a write."""
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def block_saturation(grid: pd.DataFrame) -> pd.Series:
    """Share of runs where lengthening the masked block changes nothing at all.

    Past the readout's receptive field the extra masked steps are unreachable,
    so the forecast is not merely similar but identical. That distinguishes an
    architectural limit from a model that simply weights recent days heavily.
    """
    block = grid[grid.kind.eq("block_missing")]
    wide = block.pivot_table(
        index=["model", "horizon", "model_seed"], columns="level", values="rmse"
    )
    identical = (wide[3.0] - wide[7.0]).abs() < 1e-12
    return identical.groupby(level="model").mean()


def macros(grid: pd.DataFrame, fields: pd.DataFrame, out: Path) -> None:
    indexed = fields.set_index("model")
    reach = indexed.receptive_field
    control = indexed.control_receptive_field
    saturation = block_saturation(grid)
    corrupted = grid[grid.kind.ne("clean")]
    names = {"trustkan": "Trust", "kan": "Kan", "transformer": "Transformer"}
    lines = ["% Generated by scripts/analyze_robustness.py -- do not edit by hand."]

    def macro(name: str, value: str) -> None:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    for model, short in names.items():
        subset = corrupted[corrupted.model.eq(model)]
        if subset.empty:
            continue
        macro(f"robustField{short}", f"{int(reach[model])}")
        macro(f"robustControl{short}", f"{int(control[model])}")
        macro(f"robustSaturated{short}", f"{100 * saturation.get(model, 0):.0f}\\%")
        block = subset[subset.kind.eq("block_missing")]
        macro(f"robustBlockOne{short}", pct(block[block.level.eq(1)]))
        macro(f"robustBlockThree{short}", pct(block[block.level.eq(3)]))
        macro(f"robustBlockSeven{short}", pct(block[block.level.eq(7)]))
        noise = subset[subset.kind.eq("noise") & subset.level.eq(0.20)]
        macro(f"robustNoise{short}", pct(noise))
        missing = subset[subset.kind.eq("random_missing") & subset.level.eq(0.40)]
        macro(f"robustMissing{short}", pct(missing))
    macro("robustHistory", f"{int(fields.history.iloc[0])}")
    macro("robustFieldHorizons", f"{int(fields.horizons.iloc[0])}")
    macro("robustSeeds", f"{grid.model_seed.nunique()}")
    macro("robustRuns", f"{len(grid.groupby(['model', 'horizon', 'model_seed']))}")
    macro("robustLevels", f"{corrupted.groupby(['kind', 'level']).ngroups}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {log_path(out)}")


def pct(frame: pd.DataFrame) -> str:
    return "--" if frame.empty else f"{100 * frame.relative_increase.mean():.1f}\\%"


def main(outdir: Path) -> None:
    # A relative --outdir, which is how docs/RESULT_PRODUCTION_WORKFLOW.md
    # invokes this script, used to abort between the two output files and leave
    # the table regenerated and its macros stale.
    outdir = Path(outdir).resolve()
    print("receptive fields")
    fields = receptive_fields()
    if not GRID.exists():
        raise SystemExit(
            f"missing {GRID.relative_to(ROOT)}; run scripts/run_robustness_campaign.py"
        )
    grid = pd.read_csv(GRID)
    print("corruption grid")
    robustness_table(grid, fields, outdir / "cet_robustness.tex")
    macros(grid, fields, outdir / "cet_robustness_macros.tex")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default=str(ROOT / "paper" / "tables"))
    args = parser.parse_args()
    main(Path(args.outdir))
