"""Summarize the corruption sweep and measure the mechanism behind it.

The sweep's most distinctive result is that masking the most recent history
block costs far more than any noise or scattered-missingness level, and that the
cost stops growing once the block passes a certain length. That saturation point
is a property of the architecture, not of the data: it is the number of trailing
timesteps the readout can still see.

This module measures that number directly, by perturbing one timestep at a time
and recording the furthest position back that still moves the forecast. Reported
beside the sweep, it turns "the model is fragile to recent gaps" into a
statement about how much of the history each architecture actually consumes.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import torch

try:
    import _bootstrap  # noqa: F401  # file-path execution
except ModuleNotFoundError:
    from scripts import _bootstrap  # noqa: F401  # module execution

from scripts.run_cet_benchmark import build_model, load_config
from scripts.run_robustness_campaign import MODELS

ROOT = Path(__file__).resolve().parents[1]
GRID = ROOT / "results" / "robustness" / "aggregated" / "cet_robustness_grid.csv"
LABELS = {"trustkan": "TrustKAN", "kan": "KAN (plain)", "transformer": "Transformer"}
KIND_LABELS = {
    "noise": "Gaussian noise",
    "random_missing": "Random missing",
    "block_missing": "Recent block missing",
}
HORIZONS = (1, 7, 30, 90)


def forecast(model, x: torch.Tensor) -> torch.Tensor:
    out = model(x)
    return out["point"] if isinstance(out, dict) else out


def receptive_field(model, history: int, tolerance: float = 1e-6) -> int:
    """Trailing timesteps that can still change the forecast.

    A model that consumes its whole window returns the window length; one whose
    readout sees only the end of the sequence returns that much smaller number,
    and the difference is what the block-missing column measures.
    """
    model = model.eval()
    base = torch.zeros(1, history, 1)
    with torch.no_grad():
        reference = forecast(model, base)
        reach = 0
        for offset in range(history):
            probe = base.clone()
            probe[0, history - 1 - offset, 0] = 10.0
            if not torch.allclose(forecast(model, probe), reference, atol=tolerance):
                reach = offset + 1
    return reach


def receptive_fields(config: str) -> pd.DataFrame:
    cfg = load_config(config)
    history = int(cfg["window"]["history"])
    rows = []
    for name in MODELS:
        torch.manual_seed(0)
        model = build_model(name, history, HORIZONS[0], seed=0)
        reach = receptive_field(model, history)
        rows.append(
            {
                "model": name,
                "history": history,
                "receptive_field": reach,
                "history_used": reach / history,
            }
        )
        print(f"  {LABELS[name]:<12} sees {reach} of {history} timesteps")
    return pd.DataFrame(rows)


def robustness_table(grid: pd.DataFrame, fields: pd.DataFrame, out: Path) -> None:
    stats = (
        grid[grid.kind.ne("clean")]
        .groupby(["model", "kind", "level"])
        .relative_increase.mean()
        .mul(100)
    )
    reach = fields.set_index("model").receptive_field
    lines = [
        "% Generated by scripts/analyze_robustness.py -- do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Robustness on CET: percentage increase in test RMSE over the "
        r"clean forecast, averaged over four horizons and five seeds, on the "
        r"pre-registered corruption grid applied to test histories only. Masking "
        r"the most recent days costs far more than any other corruption, and for "
        r"TrustKAN the cost stops growing past three days, which is the number of "
        r"trailing timesteps its readout can see.}",
        r"\label{tab:cet_robustness}",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Corruption & Level & "
        + " & ".join(LABELS[name] for name in MODELS)
        + r" \\",
        r"\midrule",
    ]
    for kind, label in KIND_LABELS.items():
        levels = sorted({level for name, k, level in stats.index if k == kind})
        for index, level in enumerate(levels):
            cells = []
            for name in MODELS:
                key = (name, kind, level)
                cells.append(f"{stats[key]:.1f}" if key in stats.index else "--")
            shown = f"{level:g}" if kind != "block_missing" else f"{int(level)}\\,d"
            first = label if index == 0 else ""
            lines.append(f"{first} & {shown} & " + " & ".join(cells) + r" \\")
        lines.append(r"\addlinespace")
    lines += [
        r"\midrule",
        r"History visible to the readout & &"
        + " & ".join(
            f" {int(reach[name])} of {int(fields.history.iloc[0])} " for name in MODELS
        )
        + r" \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table*}",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {out.relative_to(ROOT)}")


def macros(grid: pd.DataFrame, fields: pd.DataFrame, out: Path) -> None:
    reach = fields.set_index("model").receptive_field
    corrupted = grid[grid.kind.ne("clean")]
    names = {"trustkan": "Trust", "kan": "Kan", "transformer": "Transformer"}
    lines = ["% Generated by scripts/analyze_robustness.py -- do not edit by hand."]

    def macro(name: str, value: str) -> None:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    for model, short in names.items():
        subset = corrupted[corrupted.model.eq(model)]
        if subset.empty:
            continue
        macro(f"robustField{short}", f"{int(reach[model])}")
        block = subset[subset.kind.eq("block_missing")]
        macro(f"robustBlockOne{short}", pct(block[block.level.eq(1)]))
        macro(f"robustBlockThree{short}", pct(block[block.level.eq(3)]))
        macro(f"robustBlockSeven{short}", pct(block[block.level.eq(7)]))
        noise = subset[subset.kind.eq("noise") & subset.level.eq(0.20)]
        macro(f"robustNoise{short}", pct(noise))
        missing = subset[subset.kind.eq("random_missing") & subset.level.eq(0.40)]
        macro(f"robustMissing{short}", pct(missing))
    macro("robustHistory", f"{int(fields.history.iloc[0])}")
    macro("robustSeeds", f"{grid.model_seed.nunique()}")
    macro("robustRuns", f"{len(grid.groupby(['model', 'horizon', 'model_seed']))}")
    macro("robustLevels", f"{corrupted.groupby(['kind', 'level']).ngroups}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {out.relative_to(ROOT)}")


def pct(frame: pd.DataFrame) -> str:
    return "--" if frame.empty else f"{100 * frame.relative_increase.mean():.1f}\\%"


def main(config: str, outdir: Path) -> None:
    print("receptive fields")
    fields = receptive_fields(config)
    aggregated = ROOT / "results" / "robustness" / "aggregated"
    aggregated.mkdir(parents=True, exist_ok=True)
    fields.to_csv(aggregated / "cet_receptive_fields.csv", index=False)
    if not GRID.exists():
        raise SystemExit(
            f"missing {GRID.relative_to(ROOT)}; run scripts/run_robustness_campaign.py"
        )
    grid = pd.read_csv(GRID)
    print("corruption grid")
    robustness_table(grid, fields, outdir / "cet_robustness.tex")
    macros(grid, fields, outdir / "cet_robustness_macros.tex")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/cet.yaml")
    parser.add_argument("--outdir", default=str(ROOT / "paper" / "tables"))
    args = parser.parse_args()
    main(args.config, Path(args.outdir))
