"""Generate the manuscript's CET tables directly from the frozen ledgers.

The manuscript rule is that no numerical value is typed by hand, so every table
in the results section is emitted here from `results/aggregated` and
`results/reliability/aggregated`. Runs whose code fingerprint differs from the
current one are dropped rather than silently averaged in.

This module is deliberately outside the `code_sha256` set (which covers the
runners and `src/`), so regenerating tables never invalidates a completed run.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path

import pandas as pd

import _bootstrap  # noqa: F401  # repository-root import setup

ROOT = Path(__file__).resolve().parents[1]
BENCHMARK_LEDGER = ROOT / "results" / "aggregated" / "cet_full_runs.csv"
RELIABILITY_LEDGER = (
    ROOT / "results" / "reliability" / "aggregated" / "cet_reliability_full_runs.csv"
)
COMPARISON_INDEX = (
    ROOT / "results" / "statistical_tests" / "cet_primary" / "primary_comparisons_index.json"
)
HORIZONS = (1, 7, 30, 90)
MODEL_LABELS = {
    "persistence": "Persistence",
    "svr": "SVR",
    "random_forest": "Random forest",
    "mlp": "MLP",
    "lstm": "LSTM",
    "gru": "GRU",
    "tcn": "TCN",
    "transformer": "Transformer",
    "kan": "KAN (plain)",
    "trustkan": "TrustKAN (ours)",
}
MODEL_ORDER = list(MODEL_LABELS)


def load_ok(path: Path, expected_fingerprint: str) -> pd.DataFrame:
    """Load a ledger and keep only runs produced by the current code.

    A ledger regenerated before a source change still parses cleanly and still
    reports plausible numbers, so majority-voting on the fingerprint is unsafe:
    an entirely stale ledger looks unanimous. The fingerprint is therefore
    checked against the live source tree, and a ledger that contributes nothing
    current is a hard error rather than an empty table.
    """
    frame = pd.read_csv(path)
    ok = frame[frame.status.eq("ok")].copy()
    if ok.empty:
        raise ValueError(f"No successful runs in {path}")
    current = ok[ok.code_sha256.eq(expected_fingerprint)]
    if current.empty:
        found = ", ".join(sorted({f[:12] for f in ok.code_sha256}))
        raise SystemExit(
            f"{path.relative_to(ROOT)} holds no run matching the current code "
            f"fingerprint {expected_fingerprint[:12]} (found: {found}). "
            "Re-run the campaign's --collect-only step before regenerating tables."
        )
    stale = len(ok) - len(current)
    if stale:
        print(f"  dropping {stale} run(s) from superseded code fingerprints")
    return current


def fmt(value, digits=3):
    return "--" if pd.isna(value) else f"{value:.{digits}f}"


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
    print(f"  wrote {path.relative_to(ROOT)}")


def benchmark_table(bench: pd.DataFrame, out: Path) -> None:
    stats = bench.groupby(["model", "horizon"]).rmse.agg(["mean", "std", "size"])
    best = {h: stats.xs(h, level="horizon")["mean"].idxmin() for h in HORIZONS}
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{CET test RMSE (\degC), mean $\pm$ standard deviation over "
        r"five seeds. Deterministic baselines use a single run. Bold marks the best "
        r"model at each horizon. TrustKAN never attains it.}",
        r"\label{tab:cet_rmse}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Model & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    for model in MODEL_ORDER:
        if model not in stats.index.get_level_values("model"):
            continue
        cells = []
        for horizon in HORIZONS:
            if (model, horizon) not in stats.index:
                cells.append("--")
                continue
            row = stats.loc[(model, horizon)]
            cell = fmt(row["mean"])
            if row["size"] > 1 and pd.notna(row["std"]):
                cell += rf"\,$\pm$\,{row['std']:.3f}"
            if best[horizon] == model:
                cell = rf"\textbf{{{cell}}}"
            cells.append(cell)
        lines.append(f"{MODEL_LABELS[model]} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


def reliability_table(rel: pd.DataFrame, out: Path) -> None:
    nominal = float(rel.nominal_coverage.iloc[0])
    stats = rel.groupby("horizon").agg(
        marginal=("conformal_marginal_coverage", "mean"),
        joint=("conformal_joint_coverage", "mean"),
        simultaneous=("simultaneous_joint_coverage", "mean"),
        width=("conformal_mean_width", "mean"),
        score=("conformal_interval_score", "mean"),
    )
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{Conformal calibration on CET at nominal coverage {nominal:.2f}, "
        r"averaged over five seeds. Marginal coverage holds, as split conformal "
        r"guarantees; per-origin joint coverage collapses with lead time.}",
        r"\label{tab:cet_calibration}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Quantity & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    rows = [
        ("Marginal coverage", "marginal", 3),
        ("Joint coverage", "joint", 3),
        ("Simultaneous coverage", "simultaneous", 3),
        (r"Mean width (\degC)", "width", 2),
        (r"Interval score (\degC)", "score", 2),
    ]
    for label, column, digits in rows:
        cells = [fmt(stats.loc[h, column], digits) if h in stats.index else "--" for h in HORIZONS]
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


def selective_table(rel: pd.DataFrame, out: Path) -> None:
    stats = rel.groupby("horizon").agg(
        rmse=("rmse", "mean"),
        fused=("fused_aurc", "mean"),
        width=("width_only_aurc", "mean"),
        shift=("shift_only_aurc", "mean"),
        auroc=("error_detection_auroc", "mean"),
        spearman=("reliability_spearman", "mean"),
    )
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Selective prediction on CET, averaged over five seeds. Lower AURC "
        r"is better. The fused reliability score loses to its own width-only "
        r"component at every horizon, and its top-error AUROC is at chance.}",
        r"\label{tab:cet_selective}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Quantity & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    rows = [
        ("RMSE, no abstention", "rmse", 3, False),
        ("AURC, fused score", "fused", 3, False),
        ("AURC, width only", "width", 3, True),
        ("AURC, shift only", "shift", 3, False),
        ("Top-error AUROC", "auroc", 3, False),
        (r"Error--reliability $\rho$", "spearman", 3, False),
    ]
    for label, column, digits, bold in rows:
        cells = []
        for horizon in HORIZONS:
            cell = fmt(stats.loc[horizon, column], digits) if horizon in stats.index else "--"
            cells.append(rf"\textbf{{{cell}}}" if bold and cell != "--" else cell)
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


def comparison_table(index_path: Path, out: Path) -> None:
    """Tabulate the pre-specified paired-bootstrap family."""
    rows = json.loads(index_path.read_text(encoding="utf-8"))
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Pre-specified paired comparisons on CET. $\Delta$RMSE is the mean "
        r"difference (TrustKAN minus the comparator; negative favours TrustKAN). The "
        r"last column counts, of five seed-matched pairs, how many favour the "
        r"comparator under a circular moving-block bootstrap over forecast origins "
        r"with Holm correction applied across each comparator's full family of twenty "
        r"comparisons. TrustKAN wins none of the forty.}",
        r"\label{tab:cet_paired}",
        r"\begin{tabular}{llcc}",
        r"\toprule",
        r"Comparator & Horizon & $\Delta$RMSE & Comparator wins \\",
        r"\midrule",
    ]
    for i, row in enumerate(rows):
        if i and rows[i - 1]["model_b"] != row["model_b"]:
            lines.append(r"\midrule")
        label = MODEL_LABELS.get(row["model_b"], row["model_b"])
        name = label if i == 0 or rows[i - 1]["model_b"] != row["model_b"] else ""
        lines.append(
            f"{name} & $h={row['horizon']}$ & "
            f"{row['mean_rmse_difference']:+.3f} & "
            f"{row['b_better']}/{row['n_pairs']} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


ABLATION_LEDGER = (
    ROOT / "results" / "ablations" / "aggregated" / "ablations_cet_full_runs.csv"
)
ABLATION_RUNS = ROOT / "results" / "ablations" / "runs" / "ablations_cet_full"
TRAINED_ABLATIONS = {
    "A0": "Full TrustKAN",
    "A1": "KAN encoder $\\to$ budget-matched MLP",
    "A2": "No quantile head",
    "A9": "Mean-pooled readout (superseded)",
}


def trained_ablation_table(abl: pd.DataFrame, out: Path) -> None:
    stats = abl.groupby(["ablation_id", "horizon"]).rmse.agg(["mean", "std"])
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Trained ablations on CET, test RMSE (\degC) as mean $\pm$ standard "
        r"deviation over five seeds. Replacing the KAN mapping with a budget-matched "
        r"MLP (A1) changes accuracy by less than the seed spread at every horizon, so "
        r"the KAN layer contributes nothing measurable. A9 preserves the superseded "
        r"mean-pooled readout of Section~\ref{sec:correction}.}",
        r"\label{tab:cet_ablation}",
        r"\begin{tabular}{llcccc}",
        r"\toprule",
        r"ID & Variant & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    for identifier, label in TRAINED_ABLATIONS.items():
        if identifier not in stats.index.get_level_values("ablation_id"):
            continue
        cells = []
        for horizon in HORIZONS:
            if (identifier, horizon) not in stats.index:
                cells.append("--")
                continue
            row = stats.loc[(identifier, horizon)]
            cells.append(rf"{row['mean']:.3f}\,$\pm$\,{row['std']:.3f}")
        lines.append(f"{identifier} & {label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


def evaluation_ablation_table(out: Path) -> None:
    """Aggregate the A3--A8 recomputations stored inside each A0 record."""
    rows, adaptive = [], []
    for path in sorted(ABLATION_RUNS.glob("ablation_A0_h*_s*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        if record.get("status") != "ok":
            continue
        payload = json.loads(record["ablation_json"])
        a8 = payload["A8_static_vs_adaptive_conformal"]
        adaptive.append(
            {
                "horizon": int(record["horizon"]),
                "static_dev": a8["static_rolling_deviation"],
                "adaptive_dev": a8["adaptive_rolling_deviation"],
                "static_width": a8["static_mean_width"],
                "adaptive_width": a8["adaptive_mean_width"],
            }
        )
        rows.append(
            {
                "horizon": int(record["horizon"]),
                "A3": payload["A3_no_conformal"]["coverage_gain"],
                "A4": payload["A4_no_embedding_shift"]["aurc_gain_from_shift"],
                "A5": payload["A5_no_interval_width"]["aurc_gain_from_width"],
                "A6": payload["A6_no_fusion"]["aurc_gain_from_fusion"],
                "A7": payload["A7_no_abstention"]["rmse_reduction"],
                "A8": payload["A8_static_vs_adaptive_conformal"][
                    "rolling_deviation_improvement"
                ],
            }
        )
    if not rows:
        print("  skipping evaluation-side ablation table; no A0 records found")
        return
    stats = pd.DataFrame(rows).groupby("horizon").mean()
    adaptive_macros(pd.DataFrame(adaptive), out.with_name("cet_adaptive.tex"))
    labels = {
        "A3": ("Conformal correction", "coverage gain over raw quantiles"),
        "A4": ("Embedding shift", "AURC gain over width-only"),
        "A5": ("Interval width", "AURC gain over shift-only"),
        "A6": ("Fusion", "AURC gain over best single component"),
        "A7": ("Abstention", "RMSE reduction on retained set"),
        "A8": ("Adaptive conformal", "rolling-deviation gain over static"),
    }
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Evaluation-side ablations on CET, recomputed from the A0 artifacts "
        r"and averaged over five seeds. Each entry is the gain attributable to the "
        r"named component, so positive favours keeping it. Only conformal correction "
        r"(A3) earns its place; the shift term, the fusion, and the abstention rule "
        r"do not.}",
        r"\label{tab:cet_eval_ablation}",
        r"\begin{tabular}{llcccc}",
        r"\toprule",
        r"ID & Component (gain measured) & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    for identifier, (name, measured) in labels.items():
        cells = [
            fmt(stats.loc[h, identifier], 3) if h in stats.index else "--"
            for h in HORIZONS
        ]
        lines.append(
            f"{identifier} & {name}, {measured} & " + " & ".join(cells) + r" \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(out, lines)


EXTREMES_LEDGER = ROOT / "results" / "extremes" / "cet_extremes_runs.csv"


def extremes_table(out: Path) -> None:
    """Test-set RMSE restricted to the pre-registered extreme subsets."""
    frame = pd.read_csv(EXTREMES_LEDGER)
    stats = frame.groupby(["model", "horizon"]).either_rmse.mean()
    counts = frame.groupby("horizon")[["cold_n_origins", "warm_n_origins"]].first()
    best = {
        h: stats.xs(h, level="horizon").idxmin()
        for h in HORIZONS
        if h in stats.index.get_level_values("horizon")
    }
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Test RMSE (\degC) on the pre-registered extreme subsets, defined by "
        r"the 5th and 95th percentiles of the training targets only and labelled from "
        r"each origin's first lead. Bold marks the best model at each horizon; "
        r"TrustKAN attains it nowhere, so the extreme-event claim fails on the same "
        r"evidence as the aggregate one.}",
        r"\label{tab:cet_extremes}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Model & $h=1$ & $h=7$ & $h=30$ & $h=90$ \\",
        r"\midrule",
    ]
    for model in MODEL_ORDER:
        if model not in stats.index.get_level_values("model"):
            continue
        cells = []
        for horizon in HORIZONS:
            if (model, horizon) not in stats.index:
                cells.append("--")
                continue
            cell = fmt(stats.loc[(model, horizon)])
            if best.get(horizon) == model:
                cell = rf"\textbf{{{cell}}}"
            cells.append(cell)
        lines.append(f"{MODEL_LABELS[model]} & " + " & ".join(cells) + r" \\")
    lines += [
        r"\midrule",
        "Cold origins & "
        + " & ".join(str(int(counts.loc[h, "cold_n_origins"])) for h in HORIZONS)
        + r" \\",
        "Warm origins & "
        + " & ".join(str(int(counts.loc[h, "warm_n_origins"])) for h in HORIZONS)
        + r" \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    write(out, lines)


def dataset_macros(rel: pd.DataFrame, out: Path) -> None:
    """Describe the CET panel from the artifacts rather than from the config.

    The split sizes and the calendar span are properties of what was actually
    windowed and evaluated, so they are read back off a stored artifact.
    """
    import numpy as np

    row = rel[rel.horizon.eq(1)].iloc[0]
    total = int(row.n_train + row.n_validation + row.n_calibration + row.n_test)
    with np.load(ROOT / row.artifact_path, allow_pickle=False) as source:
        times = pd.to_datetime(source["target_time"].reshape(-1))
    last = times.max()
    first = last - pd.Timedelta(days=total - 1)
    lines = [
        "% Generated by scripts/make_paper_tables.py -- do not edit by hand.",
        rf"\newcommand{{\cetFirstYear}}{{{first.year}}}",
        rf"\newcommand{{\cetLastYear}}{{{last.year}}}",
        rf"\newcommand{{\cetSpanYears}}{{{(last - first).days / 365.25:.0f}}}",
        rf"\newcommand{{\cetSamples}}{{{total:,}}}",
        rf"\newcommand{{\cetTestStart}}{{{times.min().date()}}}",
        rf"\newcommand{{\cetTestEnd}}{{{last.date()}}}",
        rf"\newcommand{{\cetTestSamples}}{{{int(row.n_test):,}}}",
    ]
    write(out, lines)


def adaptive_macros(frame: pd.DataFrame, out: Path) -> None:
    """Macros for the A8 static-versus-adaptive conformal comparison."""
    stats = frame.groupby("horizon").mean()
    names = {1: "One", 7: "Seven", 30: "Thirty", 90: "Ninety"}
    lines = ["% Generated by scripts/make_paper_tables.py -- do not edit by hand."]
    for horizon, word in names.items():
        if horizon not in stats.index:
            continue
        row = stats.loc[horizon]
        drop = 100 * (row.static_dev - row.adaptive_dev) / row.static_dev
        cost = 100 * (row.adaptive_width - row.static_width) / row.static_width
        lines.append(rf"\newcommand{{\adaptiveDevDrop{word}}}{{{drop:.1f}\%}}")
        lines.append(rf"\newcommand{{\adaptiveWidthCost{word}}}{{{cost:.1f}\%}}")
    write(out, lines)


def derived_quantities(rel: pd.DataFrame, out: Path) -> None:
    """Emit LaTeX macros for figures quoted in prose.

    The results text needs percentage improvements and gaps that are functions
    of the table entries. Deriving them here keeps the manuscript's rule that no
    number is typed by hand, and keeps prose and tables from drifting apart.
    """
    stats = rel.groupby("horizon").agg(
        rmse=("rmse", "mean"),
        fused=("fused_aurc", "mean"),
        width=("width_only_aurc", "mean"),
        selected=("fused_selected_rmse", "mean"),
        coverage=("conformal_marginal_coverage", "mean"),
        simul_width=("simultaneous_mean_width", "mean"),
        conf_width=("conformal_mean_width", "mean"),
    )
    names = {1: "One", 7: "Seven", 30: "Thirty", 90: "Ninety"}
    lines = ["% Generated by scripts/make_paper_tables.py -- do not edit by hand."]

    def macro(name: str, value: str) -> None:
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")

    for horizon, word in names.items():
        if horizon not in stats.index:
            continue
        row = stats.loc[horizon]
        macro(f"widthGain{word}", f"{100 * (row.rmse - row.width) / row.rmse:.1f}\\%")
        macro(f"fusedGain{word}", f"{100 * (row.rmse - row.selected) / row.rmse:.1f}\\%")
        macro(f"fusedPenalty{word}", f"{row.fused - row.width:.3f}")
        macro(f"widthRatio{word}", f"{row.simul_width / row.conf_width:.1f}")
    deviation = (stats["coverage"] - float(rel.nominal_coverage.iloc[0])).abs().max()
    macro("maxCoverageDeviation", f"{100 * deviation:.1f}")
    seed_sd = pd.concat([
        rel.groupby("horizon").fused_aurc.std(),
        rel.groupby("horizon").width_only_aurc.std(),
    ])
    macro("aurcSeedSdLow", f"{seed_sd.min():.3f}")
    macro("aurcSeedSdHigh", f"{seed_sd.max():.3f}")
    write(out, lines)


def provenance(bench: pd.DataFrame, rel: pd.DataFrame, out: Path) -> None:
    """Record which artifacts produced the tables so reviewers can re-derive them."""
    payload = {
        "benchmark": {
            "ledger": str(BENCHMARK_LEDGER.relative_to(ROOT).as_posix()),
            "ledger_sha256": hashlib.sha256(BENCHMARK_LEDGER.read_bytes()).hexdigest(),
            "runs": int(len(bench)),
            "code_sha256": str(bench.code_sha256.iloc[0]),
            "dataset_sha256": str(bench.dataset_sha256.iloc[0]),
        },
        "reliability": {
            "ledger": str(RELIABILITY_LEDGER.relative_to(ROOT).as_posix()),
            "ledger_sha256": hashlib.sha256(RELIABILITY_LEDGER.read_bytes()).hexdigest(),
            "runs": int(len(rel)),
            "code_sha256": str(rel.code_sha256.iloc[0]),
            "nominal_coverage": float(rel.nominal_coverage.iloc[0]),
        },
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {out.relative_to(ROOT)}")


def main(outdir: Path) -> None:
    from run_cet_benchmark import code_sha256 as benchmark_fingerprint
    from run_cet_reliability import code_sha256 as reliability_fingerprint

    print("benchmark ledger")
    bench = load_ok(BENCHMARK_LEDGER, benchmark_fingerprint())
    print("reliability ledger")
    rel = load_ok(RELIABILITY_LEDGER, reliability_fingerprint())
    benchmark_table(bench, outdir / "cet_rmse.tex")
    reliability_table(rel, outdir / "cet_calibration.tex")
    selective_table(rel, outdir / "cet_selective.tex")
    derived_quantities(rel, outdir / "cet_derived.tex")
    dataset_macros(rel, outdir / "cet_dataset.tex")
    if EXTREMES_LEDGER.exists():
        extremes_table(outdir / "cet_extremes.tex")
    else:
        print("  skipping extremes table; run scripts/run_cet_extremes.py first")
    if ABLATION_LEDGER.exists():
        from run_ablations import code_sha256 as ablation_fingerprint

        print("ablation ledger")
        abl = load_ok(ABLATION_LEDGER, ablation_fingerprint())
        trained_ablation_table(abl, outdir / "cet_ablation.tex")
        evaluation_ablation_table(outdir / "cet_eval_ablation.tex")
    else:
        print("  skipping ablation tables; run scripts/run_ablations.py first")
    if COMPARISON_INDEX.exists():
        comparison_table(COMPARISON_INDEX, outdir / "cet_paired.tex")
    else:
        print("  skipping paired table; run scripts/run_primary_comparisons.py first")
    provenance(bench, rel, outdir / "cet_tables_provenance.json")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default=str(ROOT / "paper" / "tables"))
    args = parser.parse_args()
    main(Path(args.outdir))
