r"""Assemble a self-contained, Overleaf-ready copy of the manuscript.

Overleaf compiles an uploaded snapshot rather than this repository, so a bundle
carrying one stale table is indistinguishable from a correct one until somebody
recomputes the number. The table and figure generators therefore run first, and
their code-fingerprint checks are allowed to abort the packaging step.

The bundle is then compiled in a scratch directory before it is published,
because the failures that matter here are invisible on Windows and fatal on
Overleaf: a generated table that never reached the bundle is swallowed by the
manuscript's `\IfFileExists` guards, and a filename whose case does not match
its reference still resolves on a case-insensitive filesystem.

Generated artifacts are written into the bundle rather than into `paper/`, so
packaging never rewrites the manuscript tree.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
PAPER = ROOT / "paper"
ROOT_DOCUMENT = "main.tex"
ROOT_FILES = (ROOT_DOCUMENT, "references.bib")
TREES = ("sections", "tables", "figures")
TABLE_PROVENANCE = "tables/cet_tables_provenance.json"
FIGURE_PROVENANCE = "figures/figure_provenance.json"
GENERATED_MARKER = "% Generated by scripts/"
BUILD_SUFFIXES = frozenset(
    {
        ".aux", ".bbl", ".blg", ".log", ".out", ".toc", ".lof", ".lot",
        ".fls", ".fdb_latexmk", ".gz", ".bcf", ".nav", ".snm", ".spl", ".xml",
    }
)
REFERENCE = re.compile(
    r"\\(?:input|include|IfFileExists)\s*\{([^}]*)\}"
    r"|\\includegraphics\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}"
    r"|\\bibliography\s*\{([^}]*)\}"
)
GRAPHICS_SUFFIXES = (".pdf", ".png", ".jpg", ".jpeg", ".eps")
# TeX wraps log lines at a fixed width, which splits the very warnings this
# script greps for; max_print_line widens it and unwrap() covers the case where
# the engine ignores the setting.
WRAP_WIDTH = 79


def run(command: list[str], cwd: Path) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(command)}")
    return subprocess.run(
        command,
        cwd=cwd,
        env=dict(os.environ, max_print_line="10000"),
        capture_output=True,
        text=True,
        errors="replace",
    )


def generate(script: str, outdir: Path) -> None:
    """Regenerate the derived inputs, letting a stale-ledger failure through."""
    print(f"generating {script}", flush=True)
    result = subprocess.run([sys.executable, str(SCRIPTS / script), "--outdir", str(outdir)], cwd=ROOT)
    if result.returncode:
        raise SystemExit(
            f"{script} exited {result.returncode}; the bundle would carry stale "
            "tables or figures, so packaging stops here"
        )


def generate_all(stage: Path) -> None:
    """Regenerate every derived input directly into the bundle.

    The figure generator also emits LaTeX macro files, which it places in the
    tables directory beside its --outdir, so every generator lands inside the
    staging tree and nothing is copied out of paper/.
    """
    generate("make_paper_tables.py", stage / "tables")
    generate("make_paper_figures.py", stage / "figures")
    generate("analyze_robustness.py", stage / "tables")


def is_build_artifact(path: Path) -> bool:
    """Drop LaTeX by-products, keeping figure PDFs, which are generated inputs."""
    if path.name.startswith("."):
        return True
    if path.suffix in BUILD_SUFFIXES:
        return True
    return path.suffix == ".pdf" and path.stem == Path(ROOT_DOCUMENT).stem


def is_generated(path: Path) -> bool:
    if path.suffix != ".tex":
        return False
    with path.open(encoding="utf-8") as handle:
        return handle.readline().startswith(GENERATED_MARKER)


def copy(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def collect(stage: Path) -> None:
    """Copy the hand-written sources in around the freshly generated artifacts."""
    for name in ROOT_FILES:
        copy(PAPER / name, stage / name)
    for tree in TREES:
        for path in sorted((PAPER / tree).rglob("*")):
            if not path.is_file() or is_build_artifact(path):
                continue
            target = stage / path.relative_to(PAPER)
            if target.exists():
                continue
            if is_generated(path):
                raise SystemExit(
                    f"{path.relative_to(ROOT).as_posix()} is machine-generated but "
                    "this run's generators did not emit it; copying the version in "
                    "paper/ would smuggle a stale table into the bundle"
                )
            copy(path, target)
    print(f"  collected {sum(1 for p in stage.rglob('*') if p.is_file())} files")


def graphics_dirs(main: Path) -> list[str]:
    """Read \\graphicspath rather than assuming it, so the two cannot diverge."""
    match = re.search(r"\\graphicspath\{((?:\{[^{}]*\})+)\}", main.read_text(encoding="utf-8"))
    return ["", *(re.findall(r"\{([^{}]*)\}", match.group(1)) if match else [])]


def resolve(stage: Path, relative: str) -> Path | None:
    """Resolve one path component at a time, matching case as Linux would."""
    current = stage
    for part in relative.split("/"):
        names = {entry.name for entry in current.iterdir()} if current.is_dir() else set()
        if part not in names:
            return None
        current = current / part
    return current if current.is_file() else None


def check_portability(stage: Path) -> None:
    """Walk the manuscript's dependency graph the way a Linux TeX engine would.

    A reference is an error even when it sits inside `\\IfFileExists`: the guard
    exists so a partially populated `paper/` still compiles locally, but in a
    bundle it would silently drop a table and leave its macros undefined.
    """
    dirs = graphics_dirs(stage / ROOT_DOCUMENT)
    reachable, pending, problems = set(), [ROOT_DOCUMENT], []
    while pending:
        source = pending.pop()
        if source in reachable:
            continue
        reachable.add(source)
        if not source.endswith(".tex"):
            continue
        text = (stage / source).read_text(encoding="utf-8")
        for tex_target, graphic, bibliography in REFERENCE.findall(text):
            targets = bibliography.split(",") if bibliography else [tex_target or graphic]
            for target in (name.strip() for name in targets):
                if "\\" in target or re.match(r"^(/|~|[A-Za-z]:)", target):
                    problems.append(f"{source} references a non-portable path: {target}")
                    continue
                candidates = [target]
                if graphic:
                    candidates = [
                        f"{prefix}{target}{suffix}"
                        for prefix in dirs
                        for suffix in ("", *GRAPHICS_SUFFIXES)
                        if not (suffix and Path(target).suffix)
                    ]
                elif bibliography:
                    candidates = [f"{target}.bib"]
                elif not target.endswith(".tex"):
                    candidates.append(f"{target}.tex")
                found = next((c for c in candidates if resolve(stage, c)), None)
                if found is None:
                    # A hit here means the path exists but under a different
                    # case, which is the defect that builds on Windows and fails
                    # on Overleaf, so it is named separately.
                    mismatch = any((stage / candidate).exists() for candidate in candidates)
                    problems.append(
                        f"{source} references '{target}', which "
                        + ("exists only under a different case" if mismatch else "is missing")
                    )
                    continue
                pending.append(found)
    if problems:
        raise SystemExit("bundle is not self-contained:\n  " + "\n  ".join(problems))
    unused = sorted(
        path.relative_to(stage).as_posix()
        for path in stage.rglob("*")
        if path.is_file()
        and path.relative_to(stage).as_posix() not in reachable
        and path.suffix != ".json"
    )
    for name in unused:
        print(f"  note: {name} is in the bundle but nothing inputs it")


def unwrap(text: str) -> str:
    lines: list[str] = []
    for line in text.split("\n"):
        if lines and len(lines[-1]) == WRAP_WIDTH:
            lines[-1] += line
        else:
            lines.append(line)
    return "\n".join(lines)


def inspect_log(log: Path) -> int:
    """Fail on anything Overleaf would show as a broken build or reference."""
    text = unwrap(log.read_text(encoding="utf-8", errors="replace"))
    problems = [
        line.strip()
        for line in text.split("\n")
        if line.startswith("! ")
        or "Undefined control sequence" in line
        or re.search(r"LaTeX Warning: (Reference|Citation) `", line)
        or "There were undefined" in line
        or re.search(r"(LaTeX|Package) Warning: File `.*' not found", line)
    ]
    if problems:
        raise SystemExit(
            "verification build is not clean:\n  " + "\n  ".join(dict.fromkeys(problems))
        )
    pages = re.search(r"Output written on \S+ \((\d+) pages?", text)
    if not pages:
        raise SystemExit(f"{log.name} records no output file; the build produced no PDF")
    return int(pages.group(1))


def verify(bundle: Path, scratch: Path) -> int:
    """Compile a throwaway copy and report the page count."""
    print(f"verifying build in {scratch.relative_to(ROOT).as_posix()}")
    if scratch.exists():
        shutil.rmtree(scratch)
    scratch.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(bundle, scratch)
    stem = Path(ROOT_DOCUMENT).stem
    latex = ["pdflatex", "-interaction=nonstopmode", ROOT_DOCUMENT]
    passes = (("pdflatex", latex), ("bibtex", ["bibtex", stem]), ("pdflatex", latex), ("pdflatex", latex))
    for step, command in passes:
        result = run(command, scratch)
        if step == "bibtex" and result.returncode:
            # BibTeX exits non-zero on mere warnings, so the authoritative check
            # is whether the final pdflatex pass still reports undefined
            # citations; only a missing .bib or .aux is fatal here.
            blg = (scratch / f"{stem}.blg").read_text(encoding="utf-8", errors="replace")
            if "I couldn't open" in blg:
                raise SystemExit(f"bibtex failed:\n{blg}")
            print(f"    bibtex reported warnings (exit {result.returncode})")
    log = scratch / f"{stem}.log"
    if not log.exists():
        raise SystemExit(f"pdflatex produced no log:\n{result.stdout[-2000:]}{result.stderr[-2000:]}")
    return inspect_log(log)


def write_readme(stage: Path, pages: int) -> None:
    """State the build contract and quote the checksums the artifacts carry."""
    tables = json.loads((stage / TABLE_PROVENANCE).read_text(encoding="utf-8"))
    figures = json.loads((stage / FIGURE_PROVENANCE).read_text(encoding="utf-8"))
    lines = [
        "TrustKAN-Climate manuscript bundle",
        f"Packaged by scripts/make_paper_bundle.py at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}.",
        "",
        f"Root file:       {ROOT_DOCUMENT}",
        "Document class:  IEEEtran, option [journal]. IEEEtran ships with Overleaf and",
        "                 with TeX Live, so no .cls is vendored here.",
        "Bibliography:    references.bib, bibtex with the IEEEtran style.",
        "Build sequence:  pdflatex -> bibtex -> pdflatex -> pdflatex.",
        f"Verified build:  {pages} pages, no unresolved references or citations.",
        "",
        "Every table, figure, and numeric macro is machine-generated:",
        "scripts/make_paper_tables.py writes tables/*.tex,",
        "scripts/make_paper_figures.py writes figures/*.pdf plus the macro files",
        "it emits into tables/, and scripts/analyze_robustness.py writes the",
        "corruption table and its macros. All three read run ledgers that are bound",
        "to a code fingerprint and refuse to emit anything from superseded runs. A",
        "generated file that no generator re-emits aborts packaging. No numerical",
        "value in this manuscript is typed by hand, so a hand edit to a table or a",
        "figure breaks the audit trail: change the generator and repackage instead.",
        "",
        "Provenance, read from tables/cet_tables_provenance.json and",
        "figures/figure_provenance.json:",
    ]
    for section in ("benchmark", "reliability"):
        record = tables[section]
        lines.append(f"  {section}")
        for key, value in record.items():
            lines.append(f"    {key:<22} {value}")
    lines.append("  figures")
    for key in ("code_sha256", "coverage_window", "reliability_artifacts", "ablation_artifacts"):
        lines.append(f"    {key:<22} {figures[key]}")
    write(stage / "README.txt", lines)


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def publish(stage: Path, outdir: Path) -> None:
    outdir.parent.mkdir(parents=True, exist_ok=True)
    if outdir.exists():
        shutil.rmtree(outdir)
    os.replace(stage, outdir)
    print(f"  wrote {outdir.relative_to(ROOT).as_posix()}/")


def archive(bundle: Path, out: Path) -> None:
    """Zip with the root file at the archive root, which is what Overleaf imports."""
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_name(f".{out.name}.{os.getpid()}.tmp")
    files = sorted(path for path in bundle.rglob("*") if path.is_file())
    try:
        with zipfile.ZipFile(temporary, "w", zipfile.ZIP_DEFLATED) as bundled:
            for path in files:
                bundled.write(path, path.relative_to(bundle).as_posix())
        os.replace(temporary, out)
    finally:
        if temporary.exists():
            temporary.unlink()
    print(f"  wrote {out.relative_to(ROOT).as_posix()} ({len(files)} files, {out.stat().st_size:,} bytes)")


def main(outdir: Path, out_zip: Path, scratch: Path) -> None:
    stage = outdir.with_name(f".{outdir.name}.{os.getpid()}.tmp")
    if stage.exists():
        shutil.rmtree(stage)
    try:
        generate_all(stage)
        collect(stage)
        check_portability(stage)
        pages = verify(stage, scratch)
        write_readme(stage, pages)
        publish(stage, outdir)
        archive(outdir, out_zip)
        print(f"bundle verified at {pages} pages")
    finally:
        if stage.exists():
            shutil.rmtree(stage)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default=str(ROOT / "dist" / "paper_bundle"))
    parser.add_argument("--zip", dest="out_zip", default=str(ROOT / "dist" / "trustkan_paper.zip"))
    parser.add_argument("--scratch", default=str(ROOT / "tests" / "_scratch" / "paper_bundle_build"))
    args = parser.parse_args()
    main(Path(args.outdir), Path(args.out_zip), Path(args.scratch))
